services:
  bot:
    build: .
    network_mode: "host"
    volumes:
      - ./bot:/usr/src/bot:rw
      - ./secrets:/usr/src/bot/secrets:ro
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    command: ["python3", "service-monitor.py"]
    restart: unless-stopped
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
